### ISSUE TITLE
Иметь возможность запускать команду при начале/окончании помидора

### ISSUE THREAD

**Issue by s9gf4ult** [axce1/tomacco#2]
Чтобы иметь возможность переводить месенджеры в состояние "занят" автоматически. Ну и вообще всякую автоматизацию

**Comment by s9gf4ult** [comment]
```
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "main.py", line 53, in on_btn_start
    subprocess.Popen(config.read_conf('run_commands', 'before', True))
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1463, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'notify-send "yello yoba"'
libpng warning: iCCP: known incorrect sRGB profile
```

когда в настройках команда 

`notify-send "yello yoba"`

**Comment by s9gf4ult** [comment]
А еще не правильно парсится или сохраняется конфиг
1. Ставишь галку `with start pomidor`, галка `when finish pomodor` не активна.
2. Вписываешь команду
3. Закрываешь программу
4. Открываешь программу, открываешь настройки
5. Активна галка `when finish pomodor` но команда вбита в неактивное поле под первой галкой

**Comment by axce1** [comment]
` еще не правильно парсится или сохраняется конфиг

    Ставишь галку with start pomidor
    Вписываешь команду
    Закрываешь программу
    Открываешь программу, открываешь настройки
    Активна галка when finish pomodor но команда вбита в неактивное поле под первой галкой
`

sorry but this feature is alpha

**Comment by s9gf4ult** [comment]
Это багрепорт был, а не упрек бля

**Comment by axce1** [comment]
pull to develop

**Comment by s9gf4ult** [comment]
1. Команда для старта помидора запускается, когда галка в настройках снята.
2. Команда остановки помидора не запускается, когда останавливаешь помидор по кнопке.

**Comment by axce1** [comment]
усе поправим

**Comment by s9gf4ult** [comment]
1. Если включить галку команды, но команду оставить пустой, то помидор не стартует, а в консоли

```
Traceback (most recent call last):
  File "tomacco/main.py", line 52, in on_btn_start
    utils.run('before')
  File "/home/razor/tmp/tomacco/tomacco/modules/utils.py", line 17, in run
    subprocess.Popen(cmd_list)
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1359, in _execute_child
    executable = args[0]
IndexError: list index out of range
```

**Comment by axce1** [comment]
need testing

**Comment by s9gf4ult** [comment]
stop команда запускается если остановить паузу (короткую или длинную) по кнопке. Если пауза останавливается сама, то команда не запускается. 

По окончании ПАУЗЫ команда вообще не должна запускаться никогда.

**Comment by s9gf4ult** [comment]
Команда остановки запускается, если галка команды в настройках снята (но поле заполнено командой). И по кнопке и по таймеру помидора.

**Comment by s9gf4ult** [comment]
Если в окне настроек снять галку команды останова, сохранить, закрыть программу, снова открыть программу, то в настройках галка команды останова снова оказывается включена.

**Comment by s9gf4ult** [comment]
Вроде работает.
