### ISSUE TITLE
Не сбрасывать счетчик после длинных пауз

### ISSUE THREAD

**Issue by s9gf4ult** [axce1/tomacco#6]

**Comment by axce1** [comment]
добавлено, нужно тестирование
метка develop

**Comment by s9gf4ult** [comment]
Все еще актуально. Счетчик сбрасывается в ветке `develop`.

**Comment by s9gf4ult** [comment]
Настройка "cleanup tomacco" не сохраняется между запусками.

**Comment by axce1** [comment]
update fix come... pull from develop branch

**Comment by s9gf4ult** [comment]
```
Traceback (most recent call last):
  File "tomacco/main.py", line 355, in btn_ok_click
    self.write_settings()
  File "tomacco/main.py", line 337, in write_settings
    if self.start_edit.isChecked():
AttributeError: 'QLineEdit' object has no attribute 'isChecked'
```

При нажатии на кнопку Ок в диалоге настроек

А давай ты сам протестишь?

**Comment by s9gf4ult** [comment]
> AttributeError

алсо, тебе не надоело жрать путхон ещё?

**Comment by axce1** [comment]
> При нажатии на кнопку Ок в диалоге настроек
> А давай ты сам протестишь?

да чо ты, это же нормально когда делаешь одно, а ломается другое
зделал красыво! пробуй

> ```
> AttributeError
> ```
> 
> алсо, тебе не надоело жрать путхон ещё?

к цацкелю склоняешь?

**Comment by s9gf4ult** [comment]
> % git pull 
> Already up-to-date.

Опять не запушал?

> да чо ты, это же нормально когда делаешь одно, а ломается другое

нет

**Comment by axce1** [comment]
> ```
> % git pull
> Already up-to-date.
> ```
> 
> Опять не запушал?

ну ты понял _facepalm.bmp_

>  да чо ты, это же нормально когда делаешь одно, а ломается другое
> 
> нет

наши говорят, что это норма (с)

**Comment by s9gf4ult** [comment]
Это вроде работает
