### ISSUE TITLE
Нет значка в трее в убунте 14

### ISSUE THREAD

**Issue by s9gf4ult** [axce1/tomacco#8]
Хз в чем дело, но значок в трее просто не показывается. Во всех программах показывается, в tomacco не показывается.

**Comment by s9gf4ult** [comment]
Соответственно, после закрытия окна нет возможности его вернуть, и программа не выключается.
Окружение - MATE

**Comment by axce1** [comment]
http://stackoverflow.com/questions/24853511/pyqt5-qsystemtrayicon-is-outside-actual-tray

**Comment by s9gf4ult** [comment]
ооооооооо бляяяяяяяяяяяяя.

**Comment by s9gf4ult** [comment]
закрываю тогда
